### ISSUE TITLE
Using Env Variables for AWS Keys & Temp Token

### ISSUE THREAD

**Issue by AlexOugh** [isabinin/aws-apigateway-swagger-exporter#2]
I tried to run the export command after exporting the aws keys in env variables, but it seems to still get the keys from the credential file. Is it expected? And if so, any plan to support the env variables?

And also the region value.

**Comment by isabinin** [comment]
Thanks for your feedback.
That seems like a good feature. I've just added support environment variables for AWS access credentials and AWS region (AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY and AWS_DEFAULT_REGION).
Please try the latest version.
