### ISSUE TITLE
Path prefix truncated and moved to base path

### ISSUE THREAD

**Issue by DALDEI** [isabinin/aws-apigateway-swagger-exporter#7]
Using a head build, I exported an API with 

``` yaml
basePath: "/"
...

paths:
  /service/{foo-id}
   ...
 /session
   ...
```

and all the paths were truncated by 3 chars.  Perhaps a coincidence they were the 3 chars which were shared across all paths, i.e  "/se"

The result became:

``` yaml:

basePath: "/se"
...
paths:
  rivice/{foo-id}
...
  ssion/ 

```

**Comment by isabinin** [comment]
Fixed
